# Generated by Django 4.2.7 on 2025-07-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.CharField(max_length=20),
        ),
    ]
