# Generated by Django 4.2.7 on 2025-07-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_alter_experience_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["-order"]},
        ),
        migrations.AddField(
            model_name="experience",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
